name: Deploy to Main

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Setup SSH Agent
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.STAGING_SERVER_HOST }}
          username: ${{ secrets.STAGING_SERVER_USER }}
          key: ${{ secrets.STAGING_SERVER_KEY }}
          port: 22
          script: ls -la

      # Step 3: Deploy to Staging
      # - name: Deploy to Staging Server
      #   run: |
      #     ssh-keyscan -t rsa ${{ secrets.STAGING_SERVER_HOST }} >> ~/.ssh/known_hosts
      #     ssh -o StrictHostKeyChecking=no ${{ secrets.STAGING_SERVER_USER }}@${{ secrets.STAGING_SERVER_HOST }}
